generic:
	g++ -std=c++17 -O3 -fopenmp -Wall -Wshadow -c Tetraquark.cpp -o Tetraquark-generic.o

broadwell:
	g++ -std=c++17 -O3 -fopenmp -Wall -Wshadow -march=broadwell -c Tetraquark.cpp -o Tetraquark-broadwell.o

sandybridge:
	g++ -std=c++17 -O3 -fopenmp -Wall -Wshadow -march=sandybridge -c Tetraquark.cpp -o Tetraquark-sandybridge.o

skylake:
	g++ -std=c++17 -O3 -fopenmp -Wall -Wshadow -march=skylake -c Tetraquark.cpp -o Tetraquark-skylake-mac.o
