generic:
	g++-8 -std=c++17 -O3 -fopenmp -Wall -Wshadow -c tetraquark_class.cpp -o tetraquark_class-generic.o

broadwell:
	g++-8 -std=c++17 -O3 -fopenmp -Wall -Wshadow -march=broadwell -c tetraquark_class.cpp -o tetraquark_class-broadwell.o

sandybridge:
	g++-8 -std=c++17 -O3 -fopenmp -Wall -Wshadow -march=sandybridge -c tetraquark_class.cpp -o tetraquark_class-sandybridge.o
