generic:
	g++-8 -std=c++17 -O3 -fopenmp -Wall -Wshadow -c ns_data_v2.cpp -o ns_data_v2-generic.o

broadwell:
	g++-8 -std=c++17 -O3 -fopenmp -Wall -Wshadow -march=broadwell -c ns_data_v2.cpp -o ns_data_v2-broadwell.o

sandybridge:
	g++-8 -std=c++17 -O3 -fopenmp -Wall -Wshadow -march=sandybridge -c ns_data_v2.cpp -o ns_data_v2-sandybridge.o
