generic:
	g++ -std=c++17 -O3 -fopenmp -Wall -Wshadow -c Quark.cpp -o Quark-generic.o

broadwell:
	g++ -std=c++17 -O3 -fopenmp -Wall -Wshadow -march=broadwell -c Quark.cpp -o Quark-broadwell.o

sandybridge:
	g++ -std=c++17 -O3 -fopenmp -Wall -Wshadow -march=sandybridge -c Quark.cpp -o Quark-sandybridge.o

skylake:
	g++-9 -std=c++17 -O3 -fopenmp -Wall -Wshadow -march=sandybridge -c Quark.cpp -o Quark-skylake-mac.o

