generic:
	g++-8 -std=c++17 -O3 -fopenmp -Wall -Wshadow -c ns_data.cpp -o ns_data-generic.o

broadwell:
	g++-8 -std=c++17 -O3 -fopenmp -Wall -Wshadow -march=broadwell -c ns_data.cpp -o ns_data-broadwell.o

sandybridge:
	g++-8 -std=c++17 -O3 -fopenmp -Wall -Wshadow -march=sandybridge -c ns_data.cpp -o ns_data-sandybridge.o
